os:
  - linux
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "node"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
before_script:
  - npm i -g ava codecov nyc standard
  - npm i
script:
  - npm run lint
  - npm run test
  - npm run cover

jobs:
  include:
    - stage: "Deploy"
      deploy:
        provider: npm
        email: $NPM_EMAIL_ADDR
        api_key: $NPM_API_KEY
        skip_cleanup: true
        on:
          tags: true
          branch: master

after_success:
  - npm run report